name: Install ArgoCD
description: Install ArgoCD
inputs:
  version:
    description: Version of ArgoCD to download
    required: false
    default: "v2.14.9"
  url:
    description: URL to ArgoCD
    required: true

runs:
  using: composite
  steps:
    - name: Download ArgoCD
      run: |
        if [ ! -f ./argocd ]; then
          curl -Lo argocd https://github.com/argoproj/argo-cd/releases/download/${{ inputs.version }}/argocd-linux-amd64
          chmod +x argocd
          mv argocd /usr/local/bin/
        fi
      shell: bash
    - name: ArgoCD Login
      shell: bash
      env:
        ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
      run: |
        argocd login ${{ inputs.url }}
